<?php

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_field_storage_info().
 */
function location_entity_field_storage_info(EntityTypeInterface $entity_type) {
  $fields['address'] = BaseFieldDefinition::create('address')
    ->setLabel(t('Address'))
    ->setDescription(t('The physical address of this location.'))
    ->setRevisionable(TRUE)
    ->setSettings([
      'available_countries' => [
        'GB' => 'GB',
      ],
      'fields' => [
        'administrativeArea' => 'administrativeArea',
        'locality' => 'locality',
        'dependentLocality' => 'dependentLocality',
        'postalCode' => 'postalCode',
        'addressLine1' => 'addressLine1',
        'addressLine2' => 'addressLine2',
        'sortingCode' => '0',
        'organization' => '0',
        'givenName' => '0',
        'additionalName' => '0',
        'familyName' => '0',
      ],
    ])
    ->setDisplayOptions('form', [
      'type' => 'address_default',
      'weight' => 5,
      'settings' => [
        'default_country' => 'GB',
      ],
    ])
    ->setDisplayOptions('view', [
      'type' => 'address_default',
      'weight' => 5,
    ])
    ->setDisplayConfigurable('form', TRUE)
    ->setDisplayConfigurable('view', TRUE);
  return $fields;
}
